### ISSUE TITLE
Updating README.md

### ISSUE THREAD

**Issue by Faizan711** [Olumpusgroup/Hackoctober#30]
can i update the README.md file for the repo?
can you assign me that by giving hacktoberfest tag to this issue

**Comment by Olumpusgroup** [comment]
Yes

**Comment by Faizan711** [comment]
Can you provide me with the details of the repo so i can create a good looking README.md?

**Comment by Olumpusgroup** [comment]
A repo to share codes from codeforces, codechef, hackerrank in any languages for the developer community
A repo to share DS and ML algorithms

**Comment by Faizan711** [comment]
Thanks

**Comment by Olumpusgroup** [comment]
Great Work
